### PR TITLE
More thorough bbPress compatibility and WP feature improvements.

### PR DESCRIPTION
**Pull request by ghost**
Took another whack at it to resolve some WP trash & revision encoding issues.

I believe this to be completely bbPress compatible out  of the box now.

There is some improvement on the TinyMCE bug I mentioned in the previous pull request. A TinyMCE display bug still lingers with this commit and its predecessors relating to tinymce. I'll submit a bug report with more info.

### CODE REVIEW

**Comment by NicktheGeek** [comment]
For what it's worth, I've tested this and it works well with bbPress 2.2.3.

**Comment by ghost** [comment]
Viper, Have you had the chance to test this? Is there anything else I can do to further the cause for bbPress support?

**Comment by ghost** [comment]
Sorry, I posted too soon... I see now that the dust needs to settle involving these upcoming changes:

http://core.trac.wordpress.org/ticket/21767
&
http://bbpress.trac.wordpress.org/changeset/4771

**Comment by Viper007Bond** [comment]
The actual delay is due to being busy and a procrastinator, but yes that's a blocker right now.

**Comment by ghost** [comment]
Ive just returned to this... merged your updates and ran over it one more time WP 3.6b3 and bbPress 2.3.2 It's all still working well.

I discovered and resolved two new issues. One involved double encoding when moving replies w/ bbPress and the other involved revisions getting double encoded upon restore. 

I'm thinking that closing this request, resetting my master to the current state of yours and recommitting all of this in more succinct groups ( separating bbpress from wp-revisions ) may be the best way for you to review and hopefully merge the code.

Sound good? Do you think that you'll have the time to review this anytime soon?

**Comment by Viper007Bond** [comment]
Yes, please split out features into their own pull requests. It makes it easier to commit things for me, especially bug fix vs. enhancements.

**Pull request closed without merging**
