### PR TITLE
V2&3 new keywords & values (+ src keyword reordering)

### PR DESCRIPTION
**Pull request by ivangabriele**
keywords + pre, code, small, center, caption, embed
values + resize

### CODE REVIEW

**Comment by Viper007Bond** [comment]
Did you mean to close this? :)

**Comment by ivangabriele** [comment]
Indeed I thought it would work just by adding keywords and values there but it didn't :s

I guess it's a bit more complicated. That's all about the regex, isn't it ?

**Comment by Viper007Bond** [comment]
Ah, I'm not sure. I'm not the author of the JavaScript portion of my plugin.

Try taking your issue upstream where you'll be able to get more help: https://github.com/alexgorbatchev/SyntaxHighlighter

**Comment by ivangabriele** [comment]
When I'll get a free time, I'll check the regex to see if there is a better way to differentiate selectors, properties and values through braces and colons before to check any correspondence in keywords and values ;)

**Pull request closed without merging**
